### ISSUE TITLE
SVTPlay - Can't list or play any programs

### ISSUE THREAD

**Issue by Sopor** [retrospect-addon/plugin.video.retrospect#1217] opened 2019-09-02 19:08 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

When trying to open a program it will only list the same program list or i get the error retrieving the list of items.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To see programs

### To Reproduce

1. Run Retrospect
2. Open SVT Play
3. Open a program in the list

### Debuglog

The **debug** retrospect.log can be found here:
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3566941/retrospect.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] OSX
- [ ] Raspberry-Pi
- [x] Windows
- [ ] Windows UWP

Used versions:
- Kodi version: 18.3
- Retrospect version: 5.0.4

**Comment by basrieter** [comment] 2019-09-02 21:25
SVT Completely changed......... I got some stuff to work. Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi: 

[retrospect-patch-20190902.232352.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3567119/retrospect-patch-20190902.232352.zip)

Genres/Tags and Categories are still broken, so is the search. Will ook at that tomorrow.

**Comment by Snaah** [comment] 2019-09-02 21:37
Can confirm the patch works.

**Comment by Snaah** [comment] 2019-09-02 22:05
Also reaching programs from favourites does not work.

**Comment by basrieter** [comment] 2019-09-02 22:07
> Also reaching programs from favourites does not work.

Yes, the URLs changed, so you will eventually need to update the favourites. But let me first clean up some stuff tomorrow. To tired now.

**Comment by Snaah** [comment] 2019-09-02 22:40
Update as in completely remove, then add them again? Of course, grateful for you fixing this!

**Comment by basrieter** [comment] 2019-09-03 05:20
@Snaah as in remove the favourites that broke and add new ones.

**Comment by Snaah** [comment] 2019-09-03 20:12
@basrieter Ok, will see if there's a pattern to do it manually. Got a few. :)

**Comment by Snaah** [comment] 2019-09-03 23:01
I checked. Haven't looked at the favourites files before. Too hard for me to do anything manually to them. :)

**Comment by basrieter** [comment] 2019-09-06 18:31
Please review these translations:
```
msgctxt "#30353"
msgid "Currently Playing"
msgstr "Livesändningar"

msgctxt "#30354"
msgid "Most viewed episodes"
msgstr "Mest sedda programmen just nu"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste program"

msgctxt "#30356"
msgid "Live TV"
msgstr "Live-sändning"

msgctxt "#30357"
msgid "Live Radio"
msgstr ""

msgctxt "#30358"
msgid "Episodes"
msgstr ""

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr ""

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populära"
```

**Comment by teug** [comment] 2019-09-08 08:47
Live channels also stopped working. Channels are not listed at all.

**Comment by basrieter** [comment] 2019-09-08 09:25
I noticed that, but I need somebody to look at the translations? @Snaah @Sopor

**Comment by teug** [comment] 2019-09-08 09:37
If "Live TV" is the live streamed regular channels it should be "Kanaler" as in channels. That would make "Currently playing" special live broadcasts and not a channels and then "Livesändningar" is correct.
Episodes = Avsnitt
Full list = Alla program
All the others are correct.

**Comment by basrieter** [comment] 2019-09-08 09:59
@teug Thanks!. What about "Live Radio"?

A fix for the live channels btw::
[retrospect-patch-20190908.115946.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3587489/retrospect-patch-20190908.115946.zip)

**Comment by teug** [comment] 2019-09-08 10:14
"Live Radio" could be "Radiosändningar" or simply "Radio".

The patch solves listing all the channels and playing SVT1, SVT2 and Kunskapskanalen. Barnkanalen is listed but won't play.

**Comment by basrieter** [comment] 2019-09-08 10:21
@teug Fix for Barnkanalen: [retrospect-patch-20190908.122043.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3587507/retrospect-patch-20190908.122043.zip)

**Comment by teug** [comment] 2019-09-08 10:29
All channels listed and playable with the patch.

**Comment by basrieter** [comment] 2019-09-08 11:30
I fixed the "search": [retrospect-patch-20190908.133002.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3587544/retrospect-patch-20190908.133002.zip)

**Comment by Snaah** [comment] 2019-09-08 13:09
@basrieter If "30356 Live-sändning" is kept, change it to "Livesändning".

I would suggest using only "Radio" for 30357.

Tell us where strings are to be used if you can. It will make it easier for us to help. 

Can confirm it works too. Thanks for your fix!

**Comment by basrieter** [comment] 2019-09-08 14:39
@Snaah @Sopor @teug it now looks like this:

```msgctxt "#30350"
msgid "Search"
msgstr "Sök"

msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "Programmen"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Livesändningar"

msgctxt "#30354"
msgid "Most viewed episodes"
msgstr "Mest sedda programmen just nu"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste program"

msgctxt "#30356"
msgid "Live TV"
msgstr "Kanaler"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radiosändningar"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populära"
```

**Comment by basrieter** [comment] 2019-09-08 14:40
The difference between 30353 and 30356 is last one are the Live Streams for the channels, whereas the first one is the overview of currently playing and future streams

**Comment by Sopor** [comment] 2019-09-08 14:51
Episode is more "avsnitt" and if you should use the same words as on SVTPlay it should be "Program" and not "Programmen".

```
msgctxt "#30352"
msgid "TV Shows"
msgstr "Program"

msgctxt "#30354"
msgid "Most viewed episodes"
msgstr "Mest sedda avsnitten just nu"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste avsnitten"
```

**Comment by Sopor** [comment] 2019-09-08 14:55
So you don't use the words from SVTPlay @basrieter?

**Comment by basrieter** [comment] 2019-09-08 15:13
@Sopor because I added translations for all these folders and they will be the same for all channels. This was one of the things I discussed with Team Kodi while getting it into the repository. There is not discussion about this. 

So regarding these translations: forget SVT Play and look at it from a larger perspective: even the Dutch channels will show "Senaste program" for the most recent shows. 

Besides the language it should all work now: [retrospect-patch-20190908.170825.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3587711/retrospect-patch-20190908.170825.zip)

**Comment by Sopor** [comment] 2019-09-08 15:21
In that case i would like to have it like this:

```
msgid "Search"
msgstr "Sök"

msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "Program"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Visas just nu"

msgctxt "#30354"
msgid "Most viewed episodes"
msgstr "Mest visade avsnitten"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste avsnitten"

msgctxt "#30356"
msgid "Live TV"
msgstr "Direktsänd TV"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Direktsänd Radio"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populärt"
```

**Comment by basrieter** [comment] 2019-09-08 15:27
Thanks. So why the difference between TV and Radio?

```msgctxt "#30356"
msgid "Live TV"
msgstr "Kanaler"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Direktsänd Radio"```

**Comment by Snaah** [comment] 2019-09-09 07:19
@basrieter From checking TV4 and SVT out, 30353 "Livesändningar" are streams that are broadcasted online. They can be showing on the "live TV" at the same time, but it can also be exclusive for the web, and as you say it also lists future streams. "Currently Playing" sounds wrong to me to use for that, and as such "Visas just nu" (Shown right now) might not be the best.

"Mest visade program" will be wrong because the string is about episodes, and sometimes several episodes of one program will be in the list. But using episodes in that context sounds corny to me in Swedish. My solution: Just use "Mest visade". This goes for "Senaste avsnitten" too, make it "Senaste".

I agree with @Sopor on "Program(men)".

30357 Live Radio: Do you have plans to make Swedish radio available? A "catchup" service for radio too? If so, distinguishing between "Live Radio"/"Direktsänd radio" and "Radio"/Radio (the catchup) is a must. If no Swedish stations are planned, just use "Radio".

What's the difference between msgctxt "#30363" msgid "Popular" and "#30354"msgid "Most viewed episodes"?

**Comment by Snaah** [comment] 2019-09-09 07:20
So my suggestion is like Sopor's, with these changes: 

```
msgctxt "#30354"
msgid` "Most viewed episodes"
msgstr "Mest visade"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"
```

**Comment by zynexiz** [comment] 2019-09-09 11:14
Regarding translation, shouldn't it be more like this?

msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program" (rather than just "Program")

msgctxt "#30356"
msgid "Live TV"
msgstr "Livesändningar" (for online broadcasting)

**Comment by basrieter** [comment] 2019-09-09 20:15
> 30357 Live Radio: Do you have plans to make Swedish radio available? A "catchup" service for radio too? If so, distinguishing between "Live Radio"/"Direktsänd radio" and "Radio"/Radio (the catchup) is a must. If no Swedish stations are planned, just use "Radio".

These translations are generic for all channels: I have some Dutch radio streams, that is why
 
> What's the difference between msgctxt "#30363" msgid "Popular" and "#30354"msgid "Most viewed episodes"?

`Popular` is what is being watched mostly at that moment in time. `most viewed` are those that have been watched over a longer period of time.

**Comment by basrieter** [comment] 2019-09-09 20:20
So @Sopor @Snaah @zynexiz Can somebody post a final version of the list?

```
msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program" (rather than just "Program")

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Visas just nu"

msgctxt "#30354"
msgid` "Most viewed episodes"
msgstr "Mest visade"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste"

msgctxt "#30356"
msgid "Live TV"
msgstr "Kanaler"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populärt"
```

**Comment by Snaah** [comment] 2019-09-09 23:21
@zynexiz I forgot the "Livesändningar". Good! "TV-program" or only "Program"; sure, "TV-program" is more easy for a new user.

@basrieter Ok. Then "Populära" is better than "Populärt".

Final?
```
msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Livesändningar"

msgctxt "#30354"
msgid` "Most viewed episodes"
msgstr "Mest visade"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste"

msgctxt "#30356"
msgid "Live TV"
msgstr "Kanaler"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populära"
```

**Comment by zynexiz** [comment] 2019-09-10 11:48
@Snaah Think you misunderstood, Currently Playing is not "Livesändningar", it's "Visas just nu". Live TV is Livesändningar (or alternative Live-TV). More like this?

```
msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Visas just nu"

msgctxt "#30354"
msgid` "Most viewed episodes"
msgstr "Mest sedda avsnitt"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste avsnitt"

msgctxt "#30356"
msgid "Live TV"
msgstr "Livesändningar"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populära"
```

**Comment by Snaah** [comment] 2019-09-10 14:54
@zynexiz Yeah, I was too quick when reading your comment, but I did actually miss to translate that string. :) 

**30353 "Currently Playing/Livesändningar"** is what you can find in Retrospect for SVT Play and TV4 under "Livesändningar". It corresponds to these pages: [SVT](https://www.svtplay.se/direkt) and [TV4](https://www.tv4play.se/program/live). Notice that "Livesändningar" is what TV4 uses and I think that term is better than SVT's "Direktsändningar". Since both channels list coming broadcasts, "Visas just nu (Currently Playing)" wouldn't be good. (And if it is the same for other, non-Swedish channels, it's not good for them either.)

**30356 "Live TV/Kanaler"** is what you can find in Retrospect for SVT Play under ".:Kanaler:.". No other Swedish channel has Live TV (for free). @basrieter Correct me if I'm wrong. Otherwise I still suggest my "Final?" above. Thoughts @zynexiz @Sopor @teug ?

**Comment by basrieter** [comment] 2019-09-10 15:50
@snaah there are plenty of channels that offer Live TV streams in Retrospect (many Dutch ones). But your descriptions above are correct. 

I really want to finish this tonight and push a PR to the Kodi repo!

**Comment by zynexiz** [comment] 2019-09-10 16:42
@Snaah I'm a bit conflicted. They are both correct in their way, but you are right that currently playing indicates that it's playing right now (which is not always the case). It can also be upcoming broadcasts. Direktsändningar and Livesändningar is the same thing, but "Direktsändningar" is more correct in Swedish (if you google it, it has twice as many results). So my suggestion is this;

msgctxt "#30351"
msgid "Categories"
msgstr "Kategorier"

msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Direktsändningar"

msgctxt "#30354"
msgid` "Most viewed episodes"
msgstr "Mest sedda avsnitt"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste avsnitt"

msgctxt "#30356"
msgid "Live TV"
msgstr "TV-kanaler" (instead of just Kanaler, alternative Live-TV)

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"

msgctxt "#30358"
msgid "Episodes"
msgstr "Avsnitt"

msgctxt "#30359"
msgid "Genres"
msgstr "Genrer"

msgctxt "#30360"
msgid "Full list"
msgstr "Alla program"

msgctxt "#30361"
msgid "Tags"
msgstr "Taggar"

msgctxt "#30362"
msgid "Last chance"
msgstr "Sista chansen"

msgctxt "#30363"
msgid "Popular"
msgstr "Populära"

How does that sound?

**Comment by Snaah** [comment] 2019-09-10 17:48
@zynexiz The reason you get more hits for "direktsändning(ar)" is because this word has been used since the 1940s, while "livesändning(ar)" is a word of the 2000s. The reason I think "livesändningar" is better is because of how "direktsändning" is and has been used. Direktsänd radio or TV commonly refers to TV or Radio channels continuously broadcasting, ie not how SVT has begun using it for SVT Play. In that sense, I find "livesändningar" less confusing. 

To add "TV" is not really necessary, as there is no confusion about what type of channels it is.

For why I suggest "avsnitt" to be removed, see my [previous comment](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1217#issuecomment-529332437).

@basrieter Don't want to sound too egocentrical as I suggest to PR [my suggestion](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1217#issuecomment-529704029). If you do that and it's ok with you, we can continue the discussion here after you close the issue to come to a final decision. Then someone can make a PR with it.

**Comment by zynexiz** [comment] 2019-09-10 19:52
@Snaah As I said, they both mean the same thing, but "direktsändning" is more commonly used and sounds better (but that's just my opinion). The definition of direktsändning is "radio or television broadcast that reproduces events at the same time as they occur" according to SO (Svensk Ordbok). I got confused lots of times by "Livesändningar", and thought it was the same as Live TV :)

I don' agree. The English translation for "most recent episodes" is "Senaste avsnitt". The translation for "Senaste" is just "Recent", so it is a more correct translation. Nothing corny about it :)

**Comment by basrieter** [comment] 2019-09-10 21:11
@Snaah @zynexiz As a non-Swedish speaker it is hard to decide.....so for now I will make it:

```
msgctxt "#30352"
msgid "TV Shows"
msgstr "TV-program"

msgctxt "#30353"
msgid "Currently Playing"
msgstr "Livesändningar"

msgctxt "#30354"
msgid "Most viewed episodes"
msgstr "Mest sedda avsnitt"

msgctxt "#30355"
msgid "Most recent episodes"
msgstr "Senaste avsnitt"

msgctxt "#30356"
msgid "Live TV"
msgstr "TV-kanaler"

msgctxt "#30357"
msgid "Live Radio"
msgstr "Radio"
```
For me, as a Dutch person, this makes most sense. Feel free to start a discussion on this. @zynexiz I could even invite you to our Slack

**Comment by basrieter** [comment] 2019-09-10 21:14
Please try this last patch. It also includes the fix for #1220:
[retrospect-patch-20190910.231325.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3597710/retrospect-patch-20190910.231325.zip)

**Comment by zynexiz** [comment] 2019-09-10 21:19
@basrieter Think that will work just fine, looks good :)

Thank's for the invite, don't use Slack though. I look in here now and then and see if there is something I can contribute to :)

**Comment by Sopor** [comment] 2019-09-10 21:53
These translations are totally wrong IMO.

**Closed** 2019-09-10 21:52 UTC
Labels: bug, waiting for user

**Comment by basrieter** [comment] 2019-09-10 22:07
So discuss that with each other and PR your changes. For now, this is what I am PR-ing with Kodi. I just want the SVT channel to be fixed in the repo.

**Comment by Snaah** [comment] 2019-09-10 22:32
@zynexiz Slack is a nice place otherwise! :) I'm a language nerd, so I find these discussions good. Glad you joined in.

@sopor If I understand you correctly, you want each channel to use the vocabulary that are used on its website, no matter the language set in Kodi, right? For instance "Direktsändningar" for SVT Play and "Livesändningar" for TV 4?

@basrieter If I understand you correctly, Retrospect will have one set of strings to use for all channels (really all, no matter what country), and only those strings will be translated. In other words, no special strings for individual channels. Then what I describe above as what I think Sopor wants is not going to happen?

I can understand it would be hell of a lot of strings-files to administer to have one for each channel. I would love to have it like you want, Sopor, but I can see one set of strings for each language being less of a hassle for that guy in the Netherlands. :) Bas, I understood you on wanting the PR to go. Good choice! We'll see what we think of the strings live in Retrospect. As always, thanks for your incredible work!

And for you all to sleep well,  Snah is going to tell you of a visionary Retrospect, where you can choose to customize your own strings! I would call "TV-program" "pågram" and Retrospect would be renamed to Snahtrospect.  :D

**Comment by basrieter** [comment] 2019-09-10 22:43
One of the other reasons is that currently strings are too much hardcoded, so I need to move the into .PO files. That is what I discussed with the Kodi Team. For me, it made more sense to create generic terms and translations for commonly use text.

**Comment by zynexiz** [comment] 2019-09-11 07:30
@Snaah I agree, language is a interesting thing and how different people interpret the same word differently. I always listen to "Språket i P1", if you like languages and live in Sweden I guess you know about that radio show :)

**Comment by Snaah** [comment] 2019-09-11 17:54
@basrieter Totally understandable and probably the optimal solution in this context. It would perhaps be different if it were for a commercial product, with lots of hired programmers and text editors.

@zynexiz Yeah, I'm now question my view of "direktsändning". Maybe the meaning has gradually changed with online TV? Yes, I know "Språket i P1"! Would definitely be cool to hear what they say. Honestly, I don't think using "live" (or "play" as in "playkanaler" for that matter!) is very good in general. Typical anglicisms. We got to protect our beautiful mother tongue! :) First I was surprised SAOL doesn't list live as lajv, which would be a "Swedification" of the anglicism in the veins of mail/mejl, but then I figured "lajv" means "IRL roleplaying". Wonder if situations like this are what the hours of Svenska Akademien's session are dealing with.
