### ISSUE TITLE
A specific TV show missing episodes

### ISSUE THREAD

**Issue by GetSiddan** [retrospect-addon/plugin.video.retrospect#1523] opened 2021-05-29 22:51 UTC
### Describe the bug

A specific TV Show called Big Brother Sweden where you can see the list of episodes has been cut after a specific date.
All episodes after 28th April is no longer listed since of Wednesday 26th May.

## Expected Behavior

The list of episodes should list all available episodes, as it did before 26th May

## Actual Behavior

Episodes after 28th April is no longer listed

## Possible Fix

This issue is beyond me :)

### To Reproduce

1. View the list of episodes of Big Brother Sweden by going to TV4  Play:
2. National - TV4 Play - Reality och Dokusåpor - Big Brother Sverige - Säsong 2
3. And you will see the latest episode is S02E73, but the latest as of today (29th May) is S02E99
4. https://www.tv4play.se/program/big-brother-sverige
5. Clicking the double vertical arrows on the right side next to Season 2 and 1 will switch from the first eposidos to the latest.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/ehimujilif.kodi

### Screenshots 

-

## Additional context or screenshots (if appropriate)

I couldn't continue watching the more recent episodes.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.9
- Retrospect version: 5.4.0

**Comment by basrieter** [comment] 2021-07-19 19:56
Duplicate of #1524

**Closed by basrieter** 2021-07-19 19:56 UTC
Labels: bug
