### ISSUE TITLE
Ongewenste melding "Retrospect - inloggen mislukt" bij "live tv" en bladwijzers

### ISSUE THREAD

**Issue by Johpin1** [retrospect-addon/plugin.video.retrospect#1873] opened 2024-12-18 10:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Voor het afspelen van een aflevering wordt de melding "Retrospect - inloggen mislukt" getoond bij "live tv" en bladwijzers. Ik heb mij nooit aangemeld. Bij "recent" krijg je deze melding niet.

### Steps to Reproduce

1. Ga naar "live tv"
2. Kies NPO1
3. Klik op "ok" of ga terug (onnodige actie)
4. Live tv wordt getoond

### Expected Behavior

Geen melding "inloggen mislukt" tonen

### Debuglog

https://paste.kodi.tv/ujobonizex.kodi

### Screenshots

![screen_2](https://github.com/user-attachments/assets/99ab17d9-2553-4ed8-8d65-b318f6c824d8)

### Your Environment

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] OSX
- [X] Raspberry-Pi
- [ ] Windows
- [ ] Windows UWP

### Kodi version

20.5

### Retrospect version

5.7.21

**Comment by joopdo** [comment] 2024-12-19 19:27
I have the same issue

**Comment by basrieter** [comment] 2024-12-19 20:15
Just create a NPO account and configure it to get rid of everything.

**Comment by Johpin1** [comment] 2024-12-19 21:45
I "discovered" searching in closed issues and found the solution in https://github.com/retrospect-addon/plugin.video.retrospect/issues/1842#issuecomment-2555661164 from joopdo (thanks).

The changes are in the file resources/lib/chn_class.py

No more unwanted messages for bookmarked episodes and "live tv".

**Comment by basrieter** [comment] 2024-12-19 23:41
Duplicate of #1842

**Closed by basrieter** 2024-12-19 23:41 UTC
Labels: bug
