### ISSUE TITLE
Account login for Swedish channels

### ISSUE THREAD

**Issue by zynexiz** [retrospect-addon/plugin.video.retrospect#1371] opened 2020-05-04 18:33 UTC
## Feature Request

It seems that lot of programs have been locked, and is only accessible if you have an account on several channels. Think they where open a couple of weeks ago, or something else have changed. They are marked as premium content now. Although, they are free if you have an account on the service (Dplay, Kanal 5 etc).

Some programs that's unavailable now are Trafikpoliserna, Tunnelbanan and Vägens hjältar.

### Describe the solution you'd like

It might me possible to access them if you have an account, and can use the credentials inside Retrospect to view them. Using the Android app for Dplay, it told me that I needed an account to view the free content.

I seen some options for other channels (dutch ones i believe?) that have that options. Maybe an options for some Swedish channels to?

**Comment by basrieter** [comment] 2020-05-04 18:34
Duplicate of #1364

**Closed by basrieter** 2020-05-04 18:34 UTC
Labels: enhancement

**Comment by zynexiz** [comment] 2020-05-04 18:38
Ah, how could I miss that one. Sorry for that :)

**Comment by Snaah** [comment] 2020-05-04 20:00
@basrieter I wouldn't call this a duplicate as #1364 is about DPlay only, while this is about logins for all Swedish channels that require/have them.

**Comment by basrieter** [comment] 2020-05-04 21:07
One thing at a time. Creating log-in code is a lot of work. Dplay first.
