### ISSUE TITLE
Disovery Plus login not working.

### ISSUE THREAD

**Issue by SpaerlanHejsan** [retrospect-addon/plugin.video.retrospect#1586] opened 2021-12-15 07:59 UTC
### Describe the bug

When im trying to play items on discovery+ (sweden) I get these errors 
"Could not lo on to the selected channel." 
"The selected item is not free and might not play on Kodi." 
"One or more items failed to play. 
Check the log for more information about this message" 
"The selected item does not have any streams associated"
and the debug log says "Error logging in. Invalid Arkose token."

I know this show is free to play cause its working on their website and it was working on my old setup a couple weeks ago.
I have just upgraded from running kodi/retrospect on an raspberry pi 3 to a raspberry pi 4 and ever since discovery+ stopped working.

When I look around here and google for a solution it seems the login-process have changed and its hard to solve the "im not a robot"-verification, but the strange thing is it was working for me with my old setup just a couple weeks ago and the answers on the topic is months old.
I even tried to create an all new account on discovery+ but with same error.
When I ran my old setup on a raspberry pi 3 it updated everything on startup and I get the same error there now. 
I wanted to show you that retrospect.log to see why that one was working and not this one but its the same error appears there now.
Is it the verification when I try to sign in thats causing this and its to hard to "crack" and there is no solution? Im just wondering why it was working before everything upgraded on my raspberry pi 3. 
Can I somehow copy an old file from my raspberry pi 3 to get it working again?
Thanks for all the hard work on this addon, you guys are the best!

## Expected Behavior

The login process should work and the episodes play.

## Actual Behavior

Login error.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/exohosuyec

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi 4
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.4.9

**Comment by basrieter** [comment] 2021-12-15 08:13
Duplicate of #1475. No fix for the moment.

**Closed by basrieter** 2021-12-15 08:13 UTC
Labels: bug
