### ISSUE TITLE
Python 3 support for kodi 19 (hdr)

### ISSUE THREAD

**Issue by kiss81** [retrospect-addon/plugin.video.retrospect#1341] opened 2020-03-15 19:30 UTC
Iwas wondering if there is a way to already run this plugin on a kodi build that only supports Python 3.
I want to use this build as it adds native HDR support, but it seems to only support Python 3.
https://forum.kodi.tv/showthread.php?tid=349861

I saw a py3 branch. Is this something I can test run? I do have some programming experience, so I might be able to help fix bugs too.

**Comment by basrieter** [comment] 2020-03-15 19:40
There will be a Matrix build soon. I am waiting for some dependencies.

**Comment by kiss81** [comment] 2020-03-15 20:32
> There will be a Matrix build soon. I am waiting for some dependencies.

Let me know if there is something I can code / test.

**Comment by robinwit** [comment] 2020-03-27 17:57
It seems to be working for me with the latest Matrix test build, though navigation is pretty slow. Python related?

**Comment by basrieter** [comment] 2020-03-27 18:01
Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?

**Comment by kiss81** [comment] 2020-03-27 18:08
Sure! Can I just use the latest python3 branch?

**Comment by basrieter** [comment] 2020-03-27 19:22
> Sure! Can I just use the latest python3 branch?

Yes, that should be good.

**Comment by kiss81** [comment] 2020-03-27 19:38
> It seems to be working for me with the latest Matrix test build, though navigation is pretty slow. Python related?

Can I ask how you installed this? I cloned the git repo and swithced to the kodi-repo-py3 branch and made a zip out of it to install, but no luck....

**Comment by basrieter** [comment] 2020-03-27 19:44
You don't need to. The latest Retrospect is in the Matrix repository (for the latest Nightly). But if you want to install it from here: download the zip for this branch (https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-repo-py3.zip) and install from zip.

**Comment by kiss81** [comment] 2020-03-27 20:07
> You don't need to. The latest Retrospect is in the Matrix repository (for the latest Nightly). But if you want to install it from here: download the zip for this branch (https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-repo-py3.zip) and install from zip.

Perfect. I tried this on this kodi matrix branch:
https://github.com/thexai/xbmc/releases (3.3.0 version 4 days old fork from the offical HDR matrix)

Installation from the repo worked fine. I got two times an channel update error, but after that it worked ok for some of the content. The navigation was fine for me, but my media player is bit overpowered with a i7 8700k 
One thing that didn't work are the NPO live channels. I can remember that I need to install some extra plugins on KODI 18.2, but that popup didn't come up on my Matrix build.
Here is the relevant data from my kodi.log
Let me know if there is something else I can do.
 
```
2020-03-27 20:59:28.063 T:2276   ERROR: Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 480, in play_video_item
                                                media_item = self.channelObject.process_video_item(media_item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 424, in process_video_item
                                                return data_parser.Updater(item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1287, in update_video_item_live
                                                return self.__update_video_item(item, episode_id, False)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1346, in __update_video_item
                                                error = NpoStream.add_mpd_stream_from_npo(None, episode_id, part, proxy=self.proxy, live=item.isLive)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\npostream.py", line 120, in add_mpd_stream_from_npo
                                                manifest_update=None if not live else "full")
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\mpd.py", line 47, in set_input_stream_addon_input
                                                if is_helper.check_inputstream():
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1053, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1007, in _check_drm
                                                if yesno_dialog(localize(30041), localize(30002), nolabel=localize(30028), yeslabel=localize(30038)):  # Widevine required
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\kodiutils.py", line 109, in yesno_dialog
                                                return Dialog().yesno(heading=heading, line1=message, nolabel=nolabel, yeslabel=yeslabel, autoclose=autoclose)
                                            TypeError: function missing required argument 'message' (pos 2)
2020-03-27 20:59:28.087 T:5176   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?channel=chn_nos2010&channelcode=uzgjson&action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD1890246CC20488AFD3897D6C438AF2E812331--AD4DFE6D1A7AC147D9BF23EEA329A4BDC6E975A655DD721B1E6509EBB4925BBB&rnd=91623]
2020-03-27 20:59:32.804 T:5176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.retrospect/?action=listfolder&channel=chn_nos2010&channelcode=uzgjson) failed
2020-03-27 20:59:38.286 T:5176  NOTICE: Stopping player
```

**Comment by basrieter** [comment] 2020-03-27 20:30
Right, that is indeed fixed later! You know what, give me a moment. That broke in recent ABI changes.

**Comment by basrieter** [comment] 2020-03-27 20:36
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-repo-py3.zip again and try again.

**Comment by kiss81** [comment] 2020-03-27 20:51
> Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/kodi-repo-py3.zip again and try again.

I tried this zip on a vanilla kodi user directory, but still no luck:
First time error when loading channels:

```
2020-03-27 21:45:56.750 T:1076   ERROR: Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 566, in move
                                                os.rename(src, real_dst)
                                            FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' -> 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml'
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addonsettings.py", line 1115, in update_add_on_settings_with_channels
                                                shutil.move(filename_temp, filename)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 580, in move
                                                copy_function(src, real_dst)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 266, in copy2
                                                copyfile(src, dst, follow_symlinks=follow_symlinks)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 104, in copyfile
                                                raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
                                            shutil.SameFileError: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
2020-03-27 21:45:56.757 T:1076   ERROR: Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 566, in move
                                                os.rename(src, real_dst)
                                            FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' -> 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml'
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addonsettings.py", line 1115, in update_add_on_settings_with_channels
                                                shutil.move(filename_temp, filename)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 580, in move
                                                copy_function(src, real_dst)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 266, in copy2
                                                copyfile(src, dst, follow_symlinks=follow_symlinks)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 104, in copyfile
                                                raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
                                            shutil.SameFileError: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 566, in move
                                                os.rename(src, real_dst)
                                            FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' -> 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml'
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addon.py", line 62, in run_addon
                                                plugin.Plugin(sys.argv[0], sys.argv[2], sys.argv[1])
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 105, in __init__
                                                self.show_categories()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 250, in show_categories
                                                categories = channel_register.get_categories()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\helpers\channelimporter.py", line 264, in get_categories
                                                channels = self.get_channels()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\helpers\channelimporter.py", line 234, in get_channels
                                                AddonSettings.update_add_on_settings_with_channels(valid_channels, Config)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addonsettings.py", line 1132, in update_add_on_settings_with_channels
                                                shutil.move(filename_temp, filename)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 580, in move
                                                copy_function(src, real_dst)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 266, in copy2
                                                copyfile(src, dst, follow_symlinks=follow_symlinks)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 104, in copyfile
                                                raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
                                            shutil.SameFileError: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
2020-03-27 21:45:56.759 T:1076   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'shutil.SameFileError'>
                                            Error Contents: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 566, in move
                                                os.rename(src, real_dst)
                                            FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' -> 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml'
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addonsettings.py", line 1115, in update_add_on_settings_with_channels
                                                shutil.move(filename_temp, filename)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 580, in move
                                                copy_function(src, real_dst)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 266, in copy2
                                                copyfile(src, dst, follow_symlinks=follow_symlinks)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 104, in copyfile
                                                raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
                                            shutil.SameFileError: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 566, in move
                                                os.rename(src, real_dst)
                                            FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' -> 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml'
                                            
                                            During handling of the above exception, another exception occurred:
                                            
                                            Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\retroaddon.py", line 4, in <module>
                                                addon.run_addon()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addon.py", line 62, in run_addon
                                                plugin.Plugin(sys.argv[0], sys.argv[2], sys.argv[1])
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 105, in __init__
                                                self.show_categories()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 250, in show_categories
                                                categories = channel_register.get_categories()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\helpers\channelimporter.py", line 264, in get_categories
                                                channels = self.get_channels()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\helpers\channelimporter.py", line 234, in get_channels
                                                AddonSettings.update_add_on_settings_with_channels(valid_channels, Config)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\addonsettings.py", line 1132, in update_add_on_settings_with_channels
                                                shutil.move(filename_temp, filename)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 580, in move
                                                copy_function(src, real_dst)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 266, in copy2
                                                copyfile(src, dst, follow_symlinks=follow_symlinks)
                                              File "C:\Program Files\Kodi\system\python\Lib\shutil.py", line 104, in copyfile
                                                raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
                                            shutil.SameFileError: 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.tmp.xml' and 'C:\\Users\\sander\\AppData\\Roaming\\Kodi\\addons\\plugin.video.retrospect\\resources\\settings.xml' are the same file
                                            -->End of Python script error report<--
2020-03-27 21:45:56.778 T:936   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.retrospect/
2020-03-27 21:45:56.792 T:6984   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.retrospect/) failed
2020-03-27 21:46:05.541 T:6984  NOTICE: Stopping player
```

When trying a live stream of NPO 2:

```
2020-03-27 21:46:51.669 T:7228   ERROR: Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 480, in play_video_item
                                                media_item = self.channelObject.process_video_item(media_item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 424, in process_video_item
                                                return data_parser.Updater(item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1287, in update_video_item_live
                                                return self.__update_video_item(item, episode_id, False)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1346, in __update_video_item
                                                error = NpoStream.add_mpd_stream_from_npo(None, episode_id, part, proxy=self.proxy, live=item.isLive)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\npostream.py", line 120, in add_mpd_stream_from_npo
                                                manifest_update=None if not live else "full")
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\mpd.py", line 47, in set_input_stream_addon_input
                                                if is_helper.check_inputstream():
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1053, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1007, in _check_drm
                                                if yesno_dialog(localize(30041), localize(30002), nolabel=localize(30028), yeslabel=localize(30038)):  # Widevine required
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\kodiutils.py", line 109, in yesno_dialog
                                                return Dialog().yesno(heading=heading, line1=message, nolabel=nolabel, yeslabel=yeslabel, autoclose=autoclose)
                                            TypeError: function missing required argument 'message' (pos 2)
2020-03-27 21:46:51.692 T:7244   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?channel=chn_nos2010&channelcode=uzgjson&action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD1890246CC20488AFD3897D6C438AF2E812331--090E4FEF12238BA999487AD31F9E52491A8A7378BC2CF6EBE44A0069FE378CA7&rnd=53099]
2020-03-27 21:46:56.581 T:7228   ERROR: Traceback (most recent call last):
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 480, in play_video_item
                                                media_item = self.channelObject.process_video_item(media_item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 424, in process_video_item
                                                return data_parser.Updater(item)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1287, in update_video_item_live
                                                return self.__update_video_item(item, episode_id, False)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1346, in __update_video_item
                                                error = NpoStream.add_mpd_stream_from_npo(None, episode_id, part, proxy=self.proxy, live=item.isLive)
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\npostream.py", line 120, in add_mpd_stream_from_npo
                                                manifest_update=None if not live else "full")
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\streams\mpd.py", line 47, in set_input_stream_addon_input
                                                if is_helper.check_inputstream():
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1053, in check_inputstream
                                                return self._check_drm()
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\__init__.py", line 1007, in _check_drm
                                                if yesno_dialog(localize(30041), localize(30002), nolabel=localize(30028), yeslabel=localize(30038)):  # Widevine required
                                              File "C:\Users\sander\AppData\Roaming\Kodi\addons\script.module.inputstreamhelper\lib\inputstreamhelper\kodiutils.py", line 109, in yesno_dialog
                                                return Dialog().yesno(heading=heading, line1=message, nolabel=nolabel, yeslabel=yeslabel, autoclose=autoclose)
                                            TypeError: function missing required argument 'message' (pos 2)
2020-03-27 21:46:56.592 T:7244   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?channel=chn_nos2010&channelcode=uzgjson&action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD1890246CC20488AFD3897D6C438AF2E812331--3746C956BD7AF0C8613FD8020CA83DE5E9CB2948ACF54EAEA1958D41DA5C558B&rnd=69968]
2020-03-27 21:47:00.210 T:7244   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.retrospect/?action=listcategory&category=National) failed
2020-03-27 21:47:04.520 T:7244  NOTICE: Stopping player
```

I hope this helps. Let me know if I can test something more

**Comment by basrieter** [comment] 2020-03-27 20:57
I see, but it's outside of Retrospect: `script.module.inputstreamhelper`. They will need to fix that. 

Ping @mediaminister

**Comment by mediaminister** [comment] 2020-03-27 21:24
Please test this PR: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/298

**Comment by kiss81** [comment] 2020-03-28 09:35
> Please test this PR: [emilsvennesson/script.module.inputstreamhelper#298](https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/298)

Ping @mediaminister 
Ping @basrieter 

All works like a charm here now. Thanks!

**Comment by robinwit** [comment] 2020-03-28 11:54
> Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?

`2020-03-28 12:48:07.802 T:10035    INFO: CPythonInvoker(2, /private/var/mobile/Containers/Data/Application/3B43C67A-63F1-4574-8137-8B39BB316598/Library/Caches/Kodi/addons/plugin.video.retrospect/retroaddon.py): script successfully run
2020-03-28 12:48:37.311 T:35335   DEBUG: Thread JobWorker 0x16b95b000 terminating (autodelete)
2020-03-28 12:48:37.311 T:37931   DEBUG: Thread JobWorker 0x16b843000 terminating (autodelete)
2020-03-28 12:48:37.845 T:36127   DEBUG: Thread waiting 0x16b8cf000 terminating
`

[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397060/kodi.log)

**Comment by basrieter** [comment] 2020-03-28 16:44
> > Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?
> 
> So it seems the Python execution goes very slow on my Apple TV 4K. Let me know how I can help.
> 
> ```
> 2020-03-28 12:48:07.802 T:10035    INFO: CPythonInvoker(2, /private/var/mobile/Containers/Data/Application/3B43C67A-63F1-4574-8137-8B39BB316598/Library/Caches/Kodi/addons/plugin.video.retrospect/retroaddon.py): script successfully run
> 2020-03-28 12:48:37.311 T:35335   DEBUG: Thread JobWorker 0x16b95b000 terminating (autodelete)
> 2020-03-28 12:48:37.311 T:37931   DEBUG: Thread JobWorker 0x16b843000 terminating (autodelete)
> 2020-03-28 12:48:37.845 T:36127   DEBUG: Thread waiting 0x16b8cf000 terminating
> ```
> 
> [kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397060/kodi.log)

I need a Retrospect.log with DEBUG logging enabled.

**Comment by basrieter** [comment] 2020-03-28 16:52
> > Please test this PR: [emilsvennesson/script.module.inputstreamhelper#298](https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/298)
> 
> Ping @mediaminister
> Ping @basrieter
> 
> All works like a charm here now. Thanks!
> I will inform here if I find some issues during daily usage

I can confirm that @mediaminister

**Comment by robinwit** [comment] 2020-03-28 17:21
> > > Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?
> > 
> > 
> > So it seems the Python execution goes very slow on my Apple TV 4K. Let me know how I can help.
> > ```
> > 2020-03-28 12:48:07.802 T:10035    INFO: CPythonInvoker(2, /private/var/mobile/Containers/Data/Application/3B43C67A-63F1-4574-8137-8B39BB316598/Library/Caches/Kodi/addons/plugin.video.retrospect/retroaddon.py): script successfully run
> > 2020-03-28 12:48:37.311 T:35335   DEBUG: Thread JobWorker 0x16b95b000 terminating (autodelete)
> > 2020-03-28 12:48:37.311 T:37931   DEBUG: Thread JobWorker 0x16b843000 terminating (autodelete)
> > 2020-03-28 12:48:37.845 T:36127   DEBUG: Thread waiting 0x16b8cf000 terminating
> > ```
> > 
> > 
> > [kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397060/kodi.log)
> 
> I need a Retrospect.log with DEBUG logging enabled.



> > > Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?
> > 
> > 
> > So it seems the Python execution goes very slow on my Apple TV 4K. Let me know how I can help.
> > ```
> > 2020-03-28 12:48:07.802 T:10035    INFO: CPythonInvoker(2, /private/var/mobile/Containers/Data/Application/3B43C67A-63F1-4574-8137-8B39BB316598/Library/Caches/Kodi/addons/plugin.video.retrospect/retroaddon.py): script successfully run
> > 2020-03-28 12:48:37.311 T:35335   DEBUG: Thread JobWorker 0x16b95b000 terminating (autodelete)
> > 2020-03-28 12:48:37.311 T:37931   DEBUG: Thread JobWorker 0x16b843000 terminating (autodelete)
> > 2020-03-28 12:48:37.845 T:36127   DEBUG: Thread waiting 0x16b8cf000 terminating
> > ```
> > 
> > 
> > [kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397060/kodi.log)
> 
> I need a Retrospect.log with DEBUG logging enabled.

[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397515/retrospect.log)

**Comment by robinwit** [comment] 2020-03-28 17:32
> > > Great! Can you post a debug log (so enable debugging before performing some actions) of some navigating?
> > 
> > 
> > So it seems the Python execution goes very slow on my Apple TV 4K. Let me know how I can help.
> > ```
> > 2020-03-28 12:48:07.802 T:10035    INFO: CPythonInvoker(2, /private/var/mobile/Containers/Data/Application/3B43C67A-63F1-4574-8137-8B39BB316598/Library/Caches/Kodi/addons/plugin.video.retrospect/retroaddon.py): script successfully run
> > 2020-03-28 12:48:37.311 T:35335   DEBUG: Thread JobWorker 0x16b95b000 terminating (autodelete)
> > 2020-03-28 12:48:37.311 T:37931   DEBUG: Thread JobWorker 0x16b843000 terminating (autodelete)
> > 2020-03-28 12:48:37.845 T:36127   DEBUG: Thread waiting 0x16b8cf000 terminating
> > ```
> > 
> > 
> > [kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397060/kodi.log)
> 
> I need a Retrospect.log with DEBUG logging enabled.
Attached, I can't really see a delay except when flushing/appending the log file?
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/4397541/retrospect.log)

**Comment by basrieter** [comment] 2020-03-28 20:58
So the performance from Retrospect's point looks perfect looking at the log. So for now I am closing this issue. Although we do need a new Inputstream helper.

**Closed by basrieter** 2020-03-28 20:58 UTC
Labels: enhancement

**Comment by robinwit** [comment] 2020-03-30 08:40
> So the performance from Retrospect's point looks perfect looking at the log. So for now I am closing this issue. Although we do need a new Inputstream helper.

Indeed, FWIW in kodi-20200329-cd865190-PR17576-merge-tvos the slowness is gone.
There are other issues (stream skipping) but maybe that's also related to the tvOS build not being stable yet, and not Retrospect.

**Comment by kiss81** [comment] 2020-03-30 13:58
> > So the performance from Retrospect's point looks perfect looking at the log. So for now I am closing this issue. Although we do need a new Inputstream helper.
> 
> @basrieter FWIW in kodi-20200329-cd865190-PR17576-merge-tvos the slowness is gone.
> There are other issues (stream skipping) but maybe that's also related to the tvOS build not being stable yet, and not Retrospect.

If you use the latest trunk at:
https://github.com/emilsvennesson/script.module.inputstreamhelper/
it will work

**Comment by basrieter** [comment] 2020-03-30 17:41
Yes, script.module.inputstreamhelper will most likely submit a fix soon.
