### ISSUE TITLE
Plays streams to fast. (ViaFree)

### ISSUE THREAD

**Issue by nrehn** [retrospect-addon/plugin.video.retrospect#1399] opened 2020-06-27 09:55 UTC
### Describe the bug

When playing for example the series "Elementary" or "Elven" on ViaFree(Sverige) it is played at double speed or more.

## Expected Behavior

It should be played at normal speed :)

## Actual Behavior

Plays to fast.

## Possible Fix

N/A

### To Reproduce

1. Just try to play an episode of Elementary or Elven
2.
3.

### Debuglog

---cut--- please upload to paste.kodi.tv or attach the full file.

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux / CoreELEC
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.7
- Retrospect version: 5.2.6

**Comment by basrieter** [comment] 2020-06-28 22:41
Duplicate of #1234

**Comment by basrieter** [comment] 2020-06-28 22:43
Could you re-attach a full debug Kodi and Retrospect log (don't copy paste)

**Comment by Damme** [comment] 2020-07-11 17:32
Since no log was uploaded I've attached mine.
for me it seams it plays each m3u3 clip too fast and skip to next, so the playback either jumps ahead a couple of mins or play at something like x8 for a short while and then skips to next clip. No audio present. This bug has been for a couple of months, I dont watch tv3 much myself so I never botherd to report it but since nothing has been solved I'll try to contribute.

Log file attached here:
There is no output into the logfile after playback started sadly.

https://paste.kodi.tv/uhurotudup.kodi

Let me know if you need something else, or if there is an extra debug for inputstream.adaptive to enable.

**Comment by basrieter** [comment] 2020-07-11 18:21
Please report this in https://github.com/peak3d/inputstream.adaptive/issues/335 with a Kodi debug log.

**Comment by basrieter** [comment] 2021-04-11 21:22
Let me know if this is still an issue. Closing for now.

**Closed by basrieter** 2021-04-11 21:22 UTC
Labels: bug, duplicate
