### ISSUE TITLE
No subtitles EPG live TV and NPO live / freezing EPG during play program 

### ISSUE THREAD

**Issue by Heleen-Heleen** [retrospect-addon/plugin.video.retrospect#1792] opened 2024-05-03 08:35 UTC
### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:
Kodi Omega
Retrospect 5.7.10

**Comment by basrieter** [comment] 2024-05-03 09:18
Is this a duplicate of #1793?

**Comment by Heleen-Heleen** [comment] 2024-05-03 09:55
> Is dit een duplicaat van #1793?

Yes, I couldn't delete it

**Closed** 2024-05-03 15:57 UTC
Labels: bug
