### ISSUE TITLE
Not a bug I think but it might be a glitch :D

### ISSUE THREAD

**Issue by eskimos20** [retrospect-addon/plugin.video.retrospect#1224] opened 2019-09-12 06:29 UTC
Kodi 18.4
Retrospect 5.05
Ubuntu Desktop 19:04
Installed Retrospect via Kodi repo.

Yesterday when starting Kodi and Retrospect the 5.05 version was announced but I could not upgrade it from the repo, it simply was not there. 

So I had to upgrade it via .zip file. It worked great! 

I´ve read that upgrades should be done from the repo if you installed Retrospect from the repo, but maybe there is some issue with Retrospect knowing a newer version is available but it really is not available thru the repo.

Just a comment/question.

Anyways... really nice work with Retrospect.
/Eskimos

**Comment by basrieter** [comment] 2019-09-12 07:15
Hi @eskimos20, this is caused by the Kodi mirrors not instantly updating. When a new Retrospect version is merged into the Kodi repository those changes need to be distributed over all the Kodi mirrors. This takes time. 

If I upload the zip version to GitHub it will trigger the update notification in Retrospect. That is instant. So I think I uploaded the zip to soon. I think I will either push the zip later, or remove the notification for Kodi Leia completely as it should auto update anyways.

**Closed by basrieter** 2019-09-12 07:15 UTC
Labels: bug

**Comment by eskimos20** [comment] 2019-09-13 10:53
Thanks a lot basrieter! 

/Eskimos
