### ISSUE TITLE
Retrospect on Xbox One

### ISSUE THREAD

**Issue by bcnx** [retrospect-addon/plugin.video.retrospect#1464] opened 2020-12-25 12:05 UTC
Hi,

I encountered a problem with Retrospect on an Xbox One S. When editing the login info n channels and trying to open the password field, the AddOn closes to its main screen again, so it is not possible to enter a password.
If this issue is solved, will the Retrospect addon be able to run on an Xbox One?

Cheers,

BC

**Comment by basrieter** [comment] 2020-12-25 12:18
Please stick to the issue template: I need a debug retrospect.log

**Comment by bcnx** [comment] 2020-12-25 12:20
Sure thing, I hope I can do that on Xbox, there is no interface to the local file system should it not be possible via the Addon.

**Comment by bcnx** [comment] 2020-12-25 12:23
Like I thought: I get a Retrospect error when sending the debug file ...

**Comment by basrieter** [comment] 2020-12-25 12:33
Ok, so please provide me with a debug kodi.log.

**Comment by bcnx** [comment] 2020-12-25 12:36
I have no access to the filesystem of the Xbox One. Is there another way to send it?

**Comment by basrieter** [comment] 2020-12-25 12:36
Yes, there is an add-on for Kodi that sends the log file.

**Comment by bcnx** [comment] 2020-12-25 12:38
Yes, just found out about that, one second

**Comment by bcnx** [comment] 2020-12-25 12:41
I will not do that, as the log file is larger than 1 MB. I cannot find a setting to reset the logfile though ...

**Comment by basrieter** [comment] 2020-12-25 12:43
If you restart Kodi, it will recycle the logfile. Make sure to restart Kodi, reproduce the issue, then upload the file.

**Comment by bcnx** [comment] 2020-12-25 12:50
https://paste.kodi.tv/letovocawo

**Comment by basrieter** [comment] 2020-12-25 12:54
Ok, so this is a duplicate of #1225 

There is something not working with File access from Python. Let's continue the discussion there. I will inform within the Kodi team.

**Closed by basrieter** 2020-12-25 12:54 UTC
Labels: bug

**Comment by bcnx** [comment] 2020-12-25 17:14
You mean I should use the zip file of #1125 to fix the password issue? Or is this about how to get the logfile of the Xbox?

**Comment by basrieter** [comment] 2020-12-25 20:33
I posted a new zip there that you could try to install. It should be the start of a fix for Xbox

**Comment by bcnx** [comment] 2020-12-25 21:59
OK, will attend to this as soon as I can. I'm thinking about abandoning the Rasp Pi route as I have a second Xbox laying around and I might as well try to get that thing running for Kodi. It has more performance power compared to the Pi
