### ISSUE TITLE
SvtPlay single episodes will not play

### ISSUE THREAD

**Issue by ChrisIse** [retrospect-addon/plugin.video.retrospect#1810] opened 2024-07-14 06:29 UTC
[

### Describe the bug

Some SvtPlay programmes can't be played. Example: After Work (https://www.svtplay.se/video/KkAPkdr/after-work?video=visa). It works in a browser. 
After a little testing, it seems that this is the case for single episodes, while series episodes are playable, for example https://www.svtplay.se/video/j16gWz9/advokater/avsnitt-1?info=visa. 

## Expected Behavior

The single episode should play as usual

## Actual Behavior

Single episodes won't play and gives an error message

### To Reproduce

1.  Search 'After Work' on SvtPlay
2. Play it
3.

### Debuglog

The **debug** retrospect.log can be found here:
https://paste.kodi.tv/pozugadajo

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 20.5
- Retrospect version: 5.7.13

**Comment by basrieter** [comment] 2024-07-14 06:37
Duplicate of #1808. I have not yet released a fix. Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/master.zip and see if that fixes the issue.

**Comment by ChrisIse** [comment] 2024-07-14 06:51
Yep, that fixes it. Thanks a lot, Bas!

**Closed** 2024-07-14 15:37 UTC
Labels: bug
