### ISSUE TITLE
Unable to retrieve program list TV4

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1454] opened 2020-11-30 22:16 UTC
Unable to retrieve program list when trying to open TV4play and on any program.

Attaching log.

[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/5619035/retrospect.log)

**Comment by basrieter** [comment] 2020-11-30 23:42
I think they removed the API's for TV4, Sjuan and TV12. Please use the "TV4 Play" channel for now.

**Comment by PapaJS1** [comment] 2020-12-01 11:02
I have the same issue. TV4 Play doesn't work either.
"Error retrieving the list of items."

**Comment by Grizzly7878** [comment] 2020-12-01 13:37
i have same problem even tv4 play

**Comment by basrieter** [comment] 2020-12-01 14:23
I see, that happens alter in the process. I will have a look later today.

**Comment by Grizzly7878** [comment] 2020-12-01 15:05
You did a great work !

**Comment by s0rk** [comment] 2020-12-01 20:50
I am amazed of your efforts maintaining this plugin. Very much appreciated. Thank you, sir!

**Comment by basrieter** [comment] 2020-12-01 22:45
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip and install via zip from Kodi Leia. The TV4 Play listing is very empty now (need to figure out some stuff), but it should play. TV4, Juan, etc are no longer available as separate channel.

**Comment by eldakkar** [comment] 2020-12-02 13:48
Tried the zip and it works with TV4 play listings! Thanks a lot!

**Comment by s0rk** [comment] 2020-12-02 15:54
Success here as well. Awesome, thanks!

**Comment by Espancor** [comment] 2020-12-02 19:01
Hi! I have been trying to download the link to install via zip but It doesn´t work. What can I do? 
Thanks for a great work!

**Comment by orfeous1** [comment] 2020-12-02 19:16
Not working for me either.. Kodi Matrix.

**Comment by basrieter** [comment] 2020-12-02 19:17
What Kodi version are you on?

**Comment by basrieter** [comment] 2020-12-02 19:17
> Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip and install via zip from Kodi Leia. The TV4 Play listing is very empty now (need to figure out some stuff), but it should play. TV4, Juan, etc are no longer available as separate channel.

See the part where it says: **Kodi Leia**

**Comment by orfeous1** [comment] 2020-12-02 19:18
Using TV4play website for now until a fix will be released.

**Comment by Espancor** [comment] 2020-12-02 19:19
I use Kodi Leia 18.9

**Comment by orfeous1** [comment] 2020-12-02 19:24
> I use Kodi Leia 18.9.
> My problem is that I not able to download the zip file from this site.

Same here

**Comment by orfeous1** [comment] 2020-12-02 19:26
[plugin.video.retrospect-issue-1454.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/5631567/plugin.video.retrospect-issue-1454.zip)

test

**Comment by Espancor** [comment] 2020-12-02 19:31
I don´t what I did but I did it!

**Comment by basrieter** [comment] 2020-12-02 19:34
> I use Kodi Leia 18.9.
> My problem is that I not able to download the zip file from this site.

Weird: it's just the download for the branch: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip

**Comment by Snaah** [comment] 2020-12-02 20:34
I'm not able to download it either following the link, but copying the URL to a new tab worked. Thanks for your great work. @basrieter!

**Comment by basrieter** [comment] 2020-12-02 21:38
If you re-download the zip (no clue why it won't download when clicked upon, but the "save link as" from the browser's menu seems to work) it will now also contain most of the categories agains.

**Comment by basrieter** [comment] 2020-12-02 21:39
Is there any play on tv4play.se where shows for specific day are listed?

**Comment by Grizzly7878** [comment] 2020-12-02 21:47
Yea you get TV4 pLaylist but you only get all the programs to choose from but you lose the first menu selection unfortunately.

**Comment by mulpac** [comment] 2020-12-03 14:20
Great that it is possible to watch tv4 play again, and most of the categories seem to be back again with the latest 1454.zip.

For example on "Taskmaster" and "Så mycket bättre", there are multiple seasons available on tv4play.se, but I only seem to be able to find the latest season in Retrospect.
There are some live streams (sometimes) available on tv4play.se/kanaler, but I have not found them in Retrospect.

**Comment by matsarv** [comment] 2020-12-03 15:02
> Is there any play on [tv4play.se](https://tv4play.se) where shows for specific day are listed?

I have not seen this when browsing TV4Play. (I liked the previous week, day by day).

I now only miss the frequently used "Currently playing/Livesändningar" 
This will be found under https://www.tv4play.se/program/live


You even might add two more extra folders, if you got the time for it.
```
after line 347 in create_api_swipefolder_type

        elif title.startswith("Svenska"):
            title = "Svenska serier" <- new from string.po
        elif title.startswith("Sev"):
            title = "Sevärda dokumentärer" <- new from string.po
```

Thanks for your fantastic work!

**Comment by basrieter** [comment] 2020-12-03 18:47
Ok, but would it not make more sense to make those more generic. Such as "Series" and "Documentaries" would that be possible instead of the two proposed values?

**Comment by orfeous1** [comment] 2020-12-03 19:02
> Ok, but would it not make more sense to make those more generic. Such as "Series" and "Documentaries" would that be possible instead of the two proposed values?

Im happy with your suggesstion! Make it general. You can read the title on the program/show anyways and tell if its swedish or not.

**Comment by matsarv** [comment] 2020-12-03 19:25
> Ok, but would it not make more sense to make those more generic. Such as "Series" and "Documentaries" would that be possible instead of the two proposed values?

It's OK to make them general.


I looked a bit more in the code. Why not automate the "create_api_swipefolder_type" and create the extra MediaItem for the folder listing from the JSON. Changes in folder listing and title will then be automated when changes. Less to maintain.

**Comment by basrieter** [comment] 2020-12-03 20:08
> > Ok, but would it not make more sense to make those more generic. Such as "Series" and "Documentaries" would that be possible instead of the two proposed values?
> 
> It's OK to make them general.
> 
> 
> I looked a bit more in the code. Why not automate the "create_api_swipefolder_type" and create the extra MediaItem for the folder listing from the JSON. Changes in folder listing and title will then be automated when changes. Less to maintain.

True, but some of them are already available as translations, that is why I change them. Makes it more consistent. But it is impossible to translate each and every option. Perhaps I will only translate those that are generic and then let the others just stay Swedish.

Btw: working on the seasons

**Comment by basrieter** [comment] 2020-12-03 23:32
I fixed the seasons/folders of shows. Please review by installing the zip: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip

**Comment by basrieter** [comment] 2020-12-04 00:48
Just as a warning: the new way of fetching the main list of TV Shows is giving a lot for HTTP 502 errors. Don't know why, but hat is something for tomorrow.

**Comment by matsarv** [comment] 2020-12-04 08:00
> I fixed the seasons/folders of shows. Please review by installing the zip: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip

The seasons folder are working perfect.

**Comment by basrieter** [comment] 2020-12-05 12:35
The TV Shows still error out too much. Will try an alternative approach tonight.

**Comment by matsarv** [comment] 2020-12-05 12:48
Two small fixes might be needed in 'create_api_video_asset_type'
```
line 442, UTC+1 hour for Sweden:
  broadcast_date = DateHelper.get_datetime_from_string(date, "%Y-%m-%dT%H:%M:%SZ", "UTC") + datetime.timedelta(hours=1)
line: 467, 2-digits in hour and minutes:
  item.name = "{:02d}:{:02d} - {}".format(broadcast_date.hour, broadcast_date.minute, name)
```

**Comment by basrieter** [comment] 2020-12-05 15:24
I fixed the 502 errors, please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip (use the Save link as) and install from zip in Kodi Leia.

**Comment by basrieter** [comment] 2020-12-05 15:26
> {:02d}:{:02d}

The +1 in timezone needs a proper fix. Not like this. Let me do that.

**Comment by basrieter** [comment] 2020-12-05 15:28
Timezone and datetime is fixed. Redownload the zip file and give it a try.

**Comment by matsarv** [comment] 2020-12-05 16:15
Listing TV shows and the Timezone works OK.
The 2-digits in hour and minutes does not seem to be fixed.
![1](https://user-images.githubusercontent.com/46671821/101247817-cb563000-371b-11eb-9568-9776ea0d43cb.png)
![2](https://user-images.githubusercontent.com/46671821/101247886-343da800-371c-11eb-84df-0f5f195fe1b4.png)

**Comment by orfeous1** [comment] 2020-12-05 16:43
This fixes isnt relevant to my topic. Please end it.
Should be added in a different topic.

**Comment by basrieter** [comment] 2020-12-05 17:43
Please let me close issues with a merge. The date thing is related to new code and I will fix it.

**Comment by basrieter** [comment] 2020-12-05 18:08
Please revalidate the date issue. Should be fixed now (it was there in two locations).

**Comment by matsarv** [comment] 2020-12-05 20:39
Looks very good! Everything seems to work now.

**Comment by Snaah** [comment] 2020-12-05 21:28
> This fixes isnt relevant to my topic. Please end it.
> Should be added in a different topic.

Don't be so grumpy now. ;)

Can also confirm it's working.

**Comment by basrieter** [comment] 2020-12-06 12:22
The update will appear in the Kodi repo somewhere today: https://github.com/xbmc/repo-plugins/pull/3238 

Just waiting for the repositories to sync.

**Comment by orfeous1** [comment] 2020-12-07 19:53
Still same issues for me TV4 Play.
Updated to latest Retrospect inside Kodi.

**Comment by orfeous1** [comment] 2020-12-07 19:55
The initial page in TV4 Play needs a little bit of cleanup i think. There is too many menu choices.

**Comment by basrieter** [comment] 2020-12-07 20:30
> The initial page in TV4 Play needs a little bit of cleanup i think. There is too many menu choices.

Nope, I actually added them, on request of this thread.

**Comment by basrieter** [comment] 2020-12-07 21:13
Url's changed again......so I need to do a minor fix.

**Comment by basrieter** [comment] 2020-12-07 21:39
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip again (install from zip in Kodi Leia)

**Comment by matsarv** [comment] 2020-12-08 18:00
The fix is working ok

**Closed** 2020-12-08 23:22 UTC
Labels: bug

**Comment by dobbelina** [comment] 2020-12-08 23:27
Weird, news come up as Premium/Paid here:
Latest news=>Nyheterna=>Nyhetssändningar
Or:
Senaste nyhetsprogram=>Nyheterna=>Nyhetssändningar

Surely miss the "Today" and the rest of the week listing, but i understand it's
a change made by tv4, hence not an issue that can be resolved here.
I have contacted tv4 about it, it sucks.

**Comment by basrieter** [comment] 2020-12-08 23:35
> Weird, news come up as Premium/Paid here:
> Latest news=>Nyheterna=>Nyhetssändningar
> Or:
> Senaste nyhetsprogram=>Nyheterna=>Nyhetssändningar

Please be a bit more specific. Without any knowledge of the Swedish language "weird" is a bit hard to distinguish :)

**Comment by dobbelina** [comment] 2020-12-11 07:32
I mean like this, they still plays fine though:
![bild](https://user-images.githubusercontent.com/46063764/101875706-68d1b980-3b8b-11eb-8a31-9419e3e5c937.png)

**Comment by basrieter** [comment] 2020-12-12 00:14
They actually show: `freemium = False`

**Comment by dobbelina** [comment] 2020-12-12 09:33
Strange, because if I filter like below the links disappear:
![bild](https://user-images.githubusercontent.com/46063764/101980399-48762d80-3c65-11eb-9cc9-4a68a45c20bf.png)

**Comment by basrieter** [comment] 2020-12-12 11:18
Isn't that expected? It will filter out all paid items.

**Comment by basrieter** [comment] 2020-12-12 14:39
Should I just remove the check for Paid? Are there any paid items in TV 4?

**Comment by dobbelina** [comment] 2020-12-13 08:26
> 
> 
> Isn't that expected? It will filter out all paid items.

That's just the thing, there are no premium items on tv4 any more, and especially not the news broadcast.
That's why i thought it was weird that the news were flagged as "Premium".
tv4 Premium was discontinued in 2017.
This is not a big issue at all, now when i have de-selected "Filter/Paid items".
The reason i had it activated was to filter out paid programs on Dplay earlier.

**Comment by basrieter** [comment] 2020-12-13 10:50
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip again (install from zip in Kodi Leia)

**Comment by Snaah** [comment] 2020-12-16 19:08
I can confirm it works.

I think it is a mistake to remove the other channels, as it is confusing and not as nice and consistent as it previously was. My suggestion is to keep them but as mere copies of TV 4 Play. In the info text you can put something in the veins of 

"TV4 has stopped sorting programmes by channel in their API. This is a copy of the channel TV4 play. You can remove it from the channel listing if you like."

"TV4 har slutat sortera sina program efter kanal i sitt API. Det här är en kopia av kanalen TV4 Play. Du kan ta bort den från kanallistningen om du vill

**Comment by basrieter** [comment] 2020-12-16 21:16
> I can confirm it works.
> 
> I think it is a mistake to remove the other TV4 channels, as it is confusing and not as nice and consistent as it previously was. My suggestion is to keep them but as mere copies of TV4 Play. In the info text you can put something in the veins of
> 
> "TV4 has stopped sorting programs by channel in their API. This is a copy of the channel TV4 play. You can remove this channel from the channel listing if you like."
> 
> "TV4 har slutat sortera sina program efter kanal i sitt API. Det här är en kopia av kanalen TV4 Play. Du kan ta bort den här kanalen från kanallistningen om du vill."

I did not remove them because I wanted to, They just do not exist anymore. The old API has been shut down so there is nothing I can do about that.

**Comment by orfeous1** [comment] 2020-12-16 21:27
Dplay will become Discovery+ soon so i guess there might be some fixing with dplay channel too in the future

Im not a big fan of he new tv4 play lists.. wich made me use the tv4play.se site instead.
I really liked it how it was before. Had been nice if the user could customize how the channel would look. What categories and other thing to be hidden. For me "Categories" are just unnessesary but maybe useful for others.

On the website i go to "Alla program" then click on the alphabetic character i want, click on the show and play. For now that is not how its setup on the tv4play channel in retrospect and that annoys me. It was like that before the fix/changes.
Now there are some extra clicks and stuff to navigate in particular shows..

**Comment by Snaah** [comment] 2020-12-16 21:38
> > I can confirm it works.
> > I think it is a mistake to remove the other TV4 channels, as it is confusing and not as nice and consistent as it previously was. My suggestion is to keep them but as mere copies of TV4 Play. In the info text you can put something in the veins of
> > "TV4 has stopped sorting programs by channel in their API. This is a copy of the channel TV4 play. You can remove this channel from the channel listing if you like."
> > "TV4 har slutat sortera sina program efter kanal i sitt API. Det här är en kopia av kanalen TV4 Play. Du kan ta bort den här kanalen från kanallistningen om du vill."
> 
> I did not remove them because I wanted to, They just do not exist anymore. The old API has been shut down so there is nothing I can do about that.

I know that. That's why I said keeping the channels as _copies_ of the now present only channel TV4 Play. Id est: They will be named after the live broadcast channels, just as before, but the same channel as TV4 Play.

**Comment by basrieter** [comment] 2020-12-16 21:51
Well, in the "TV4 Play" there was always a short list with sub-items. But feel free to hide any items using the "Hide item" feature:

![image](https://user-images.githubusercontent.com/1310443/102409605-a56c3d80-3fef-11eb-84a2-fe0ed7448c78.png)

and turn it into this:

![image](https://user-images.githubusercontent.com/1310443/102410628-17915200-3ff1-11eb-9c4d-143ade1f2b81.png)

I did have to fix a minor thing. So get the new https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip

And again: It feels like you guys are blaming me for TV4 removing an API. I did not do that. I merely removed the channels that broken and fixed the generic TV4 Play channel....in the structure that was already there.

**Comment by orfeous1** [comment] 2020-12-16 21:57
Thank you for the tip, didnt know that.
But that doesnt fix the structure of how the app retrieves shows/programs with a bounch of sub menus.
That was something that someone wanted in this topic. Something that i didnt request with my error message that tv4 couldnt retrieve the programs..

**Comment by basrieter** [comment] 2020-12-17 00:12
That is something TV4 Play changed. In Kodi:

![image](https://user-images.githubusercontent.com/1310443/102420699-018c8d00-4003-11eb-8bca-852215299d6a.png)

These are the actual folders/sublists for the shows that also appear on the page (e.g. https://www.tv4play.se/program/nyheterna has "Senaste nytt", "Nyhetssändningar" and, although not listed, a "Livesändningar"). 

I initially only listed the first one, but then other seasons did not appear. So now I list the subfolders if there are more than 1. If  there is just a single subfolder, I immediately list that single subfolder (so you won't even notice it being there). 

So this is something that TV4 Play changed. And although I understand that "it was not the way it was" the fact that seasons were missing was a bug in the initial fixed version. I am open for suggestions to make your life easier (and I can do a lot within Retrospect), but please keep in mind that I am bound by the API's that TV4 provides. 

So how would you like to see a better solution (that includes the seasons as well)?

**Comment by Snaah** [comment] 2020-12-17 00:27
> And again: It feels like you guys are blaming me for TV4 removing an API. I did not do that. I merely removed the channels that broken and fixed the generic TV4 Play channel....in the structure that was already there.

Oh, no! That's not at all what I meant to say or been thinking. I understand perfectly well the removal/changes are due to TV4 changing their API, and that it has nothing to do with you. Throughout all the years I've been using Retrospect, I've been so amazed for your work and swift action when something is broken. That is devotion! Fixing channels in other countries, even more amazing. 

But I'm wondering, do you get my suggestion? Keeping all TV4 channels in Retrospect but as copies of the Retrospect channel TV4 Play. All the Retrospect TV4 channels open Retrospect TV4 Play and have the info text I suggested above. I don't know Python or if it's possible at all. If it's possible, but requires a lot of work for you there's better things to spend energy on. :)

**Comment by basrieter** [comment] 2020-12-19 13:45
> But I'm wondering, do you get my suggestion? Keeping all TV4 channels in Retrospect but as copies of the Retrospect channel TV4 Play. All the Retrospect TV4 channels open Retrospect TV4 Play and have the info text I suggested above. I don't know Python or if it's possible at all. If it's possible, but requires a lot of work for you there's better things to spend energy on. :)

That should be possible, but is it that what users expect? Let me try and see if I can get the `channel` from the GraphQL data and use it to filter.

**Comment by matsarv** [comment] 2020-12-20 16:16
A final small request, if it's possible.

I know that there are "Live" folders in the TV-shows folder structure and before we had the "Currently playing/Livesändningar" that collects all the "Live" TV-shows.

At the bottom of the home page there is a link to current/upcomming live broadcasting.
![tv4 live](https://user-images.githubusercontent.com/46671821/102718111-b1554980-42e6-11eb-80bf-413e775e0162.png)

This list will be found under https://www.tv4play.se/program/live

It would be nice if the GraphQL data could provide this data.

**Comment by basrieter** [comment] 2020-12-20 17:57
Ok, fixed. Please verify https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1454.zip to see if it works. I really want to push out an update tonight, as I will not have any time to spare before Christmas.

**Comment by matsarv** [comment] 2020-12-20 18:08
Tested and the fix works perfectly.
Great job as always. Merry Christmas.
