### ISSUE TITLE
Some TV shows on NPO Plus are empty

### ISSUE THREAD

**Issue by powermarcel10** [retrospect-addon/plugin.video.retrospect#1858] opened 2024-10-22 22:17 UTC
Hi,

There are a few TV shows I cannot watch using npo. I can find the show, but when I enter it, no episodes are found. I'm getting a message; selected item has no streams availible.

Using the NPO plus app on my nvidia shield I am able to watch them. So no idea why these TV shows are empty in Retrospect. A lot of other shows (also premium) can be watched fine. 

The 2 TV shows I cannot watch are;

1985
A Spy Among Friends

If you need any other information, let me know.

**Comment by basrieter** [comment] 2024-10-23 07:49
For a next time: don't delete the template for an issue, but fill it. Providing a logfile was part of the questions. 

For now: please provide a DEBUG retrospect.log: Enable debug logging in Retrospect, reproduce the problem and then upload (don't copy paste) the full log here. You can use the built-in feature to upload the log to paste.kodi.tv.

**Comment by keiem** [comment] 2024-10-25 15:25
Same problem here.  I have empty folders in the "plus" items.  I have to say, I'm in belgium, so maybe they changed something on that side...
I will see to make a new issue with the necessary logs.

**Comment by basrieter** [comment] 2024-10-25 21:52
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/1862-empty-folders-in-npo-plus-items.zip

**Comment by keiem** [comment] 2024-10-26 06:14
Bas,

works like a charm!
Thanks a lot for the quick reply and fix!

**Comment by basrieter** [comment] 2024-10-26 09:23
Great .  will push a release soon.

**Comment by basrieter** [comment] 2024-10-26 10:21
Duplicate of #1862

**Closed by basrieter** 2024-10-26 10:21 UTC
Labels: bug
