### ISSUE TITLE
Kanal 5 and dplay Sverige  doesn't work 

### ISSUE THREAD

**Issue by cabban** [retrospect-addon/plugin.video.retrospect#1275] opened 2020-01-14 19:11 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Watch tv episodes

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 8.1.5
- Retrospect version:
5.14

**Comment by Snaah** [comment] 2020-01-14 20:42
@cabban Help @basrieter out by following the form and attaching a **debug** Retrospect log file. You have to change the log option to "Debug" in Retrospect settings.

Here it works like it should running the same setup a you. Did you restart Kodi after the latest update?

**Comment by basrieter** [comment] 2020-01-14 23:02
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20200115.000213.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4062069/retrospect-patch-20200115.000213.zip)

**Comment by cabban** [comment] 2020-01-15 15:04
> Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.
> 
> [retrospect-patch-20200115.000213.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4062069/retrospect-patch-20200115.000213.zip)

Did I do something wrong. It not working I replaced and restart kodi . 🤔

**Comment by basrieter** [comment] 2020-01-15 15:30
How did you replace it and what does not work? 

You should manually extract the files and replace them. Don't use the  "install from zip" feature. 

Also: if it is not working please attach a debug Kodi and Retrospect log.

**Comment by cabban** [comment] 2020-01-15 16:09
> How did you replace it and what does not work?
> 
> You should manually extract the files and replace them. Don't use the "install from zip" feature.
> 
> Also: if it is not working please attach a debug Kodi and Retrospect log.

I extracted and replace Swedish channel file

**Comment by basrieter** [comment] 2020-01-15 16:19
Logs?

**Comment by basrieter** [comment] 2020-01-15 17:25
@Snaah Is it working for you?

**Comment by cabban** [comment] 2020-01-15 17:30
> Logs? And what is not working? All of Retrospect, or still the same issue?

Only same issue 😀 not entirely retrospect. 
How to upload log?💚

**Comment by basrieter** [comment] 2020-01-15 18:00
https://github.com/retrospect-addon/plugin.video.retrospect/wiki/Logging

**Comment by Snaah** [comment] 2020-01-15 20:28
@basrieter Works without and with your patch here.

**Comment by walleboom** [comment] 2020-01-16 23:38
@basrieter seems to be an issue in chn_sbs.py:618, KeyError: "src".

`images = filter(lambda a: a["type"] == "image", json_data.get_value("included"))
images = filter(lambda i: "attributes" in i and "src" in i["attributes"],images)
images = {str(image["id"]): image["attributes"]["src"] for image in images}`

Fixed it for me.

**Comment by basrieter** [comment] 2020-01-17 07:58
I don't know if this is related, but please provide me with a log file of the issue that is occurring or tell me how to reproduce it.

**Comment by walleboom** [comment] 2020-01-17 09:05
@basrieter 

On
Raspberry PI 3 with OSMC
Retrospect 5.1.4

When I opened "Kanal 5" (Sweden) I got a toaster that said something along the lines of "Could not retrive list". In the log, as mentioned earlier I got: KeyError: "src" in /plugin.video.retrospect/channels/channel.se/sbs/chn_sbs.py:608 (without your patch)

When I manually check the fetched JSON there's, as mentioned earlier, an entry with type "image" but without "attributes"->"src" (Its "kind" is different -> "poster"). This explains the KeyError: "src"... it's missing "src" in "attributes"...

__update_image_lookup should pass a test with json_data:

```
{
 "includes": [
{
    "attributes" : {
      "default" : true,
      "kind" : "poster"
    },
    "id" : "667840-show-12346",
    "type" : "image"
  }
 ]
}
```

**Comment by olskar** [comment] 2020-01-17 19:07
I have applied the changes you suggested in chn.sbs.py @walleboom  but get the following:

`20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - Plugin::Error Processing FolderList
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - | Traceback (most recent call last):
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |   File "C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\plugin.py", line 388, in process_folder_list
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |     media_items = self.channelObject.process_folder_list(selected_item)
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |   File "C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 233, in process_folder_list
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |     (data, pre_items) = data_parser.PreProcessor(data)
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |   File "C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.se\sbs\chn_sbs.py", line 256, in load_programs
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |     self.__update_image_lookup(json)
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |   File "C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.se\sbs\chn_sbs.py", line 608, in __update_image_lookup
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |     images = {str(image["id"]): image["attributes"]["src"] for image in images}
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |   File "C:\Users\username\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.se\sbs\chn_sbs.py", line 608, in <dictcomp>
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - |     images = {str(image["id"]): image["attributes"]["src"] for image in images}
20200117 20:05:04 - [ERROR   ] - plugin.py            - 459  - + KeyError: 'src'
20200117 20:05:04 - [INFO    ] - addon.py             - 67   - Retrospect :: Flushing and closing logfile.
20200117 20:05:04 - [INFO    ] - addon.py             - 35   - XOT Logger :: Appending Existing logFile`

**Comment by basrieter** [comment] 2020-01-18 12:33
Let me repeat myself again: I need a full debug retrospect.log in order to reproduce the issue and check whether this fix does not cause any other issues?

**Comment by basrieter** [comment] 2020-01-18 12:56
Please install this version using the "Install from zip" option in Kodi. It is not 100% the suggested fix, but the result is the same.

[plugin.video.retrospect-5.1.4-1275.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4080700/plugin.video.retrospect-5.1.4-1275.zip)

**Comment by basrieter** [comment] 2020-01-19 17:31
Did anyone try this?

**Comment by rikast** [comment] 2020-01-20 20:18
My first post at github so please excuse any newbie errors. 
Just tried the 1275.zip-file. The listing of shows works fine now (which it didn’t prior to applying the update) but when a show is selected for playback the response is “Cannot start playback”.

**Comment by basrieter** [comment] 2020-01-20 20:29
The 'a' items are paid items and won't play.

**Comment by rikast** [comment] 2020-01-20 21:16
Thank you for your quick and firm response. 
Then they’ve changed that show to pay item at the same time. It used to work. =)
On the other hand I at least like to claim the fix is working.

**Closed** 2020-01-21 23:03 UTC
Labels: bug, channel, sweden, tobereleased
