### ISSUE TITLE
Not able to enter channel password on Xbox One

### ISSUE THREAD

**Issue by eettiennee** [retrospect-addon/plugin.video.retrospect#1265] opened 2019-11-25 14:12 UTC
### Describe the bug
Here is a clear and concise description of what the problem is:
I am able to install Retrospect on my Xbox One. The Add on is showing up in my view.
However, I'm able to enter my channel settings user name but not my password. As soon as I select password, the add on crashes.

## Expected Behavior
I can select username to enter and save my username (e.g. for Stievie). I can select password to enter my password and save.
## Actual Behavior
When I try to select "password" I expect a screen with keyboard lay out so I can enter my password. The add on crashes before I'm able to see this screen with password + keyboard lay out. I don't have the same issue for username, which is working fine.

## Possible Fix
Make sure I'm able to enter my password and save it. Otherwise the add on doesn't work on Xbox.

### To Reproduce
Install the add on and go to settings. In channel settings select Stievie (same for VRTNu) and try to enter your password after enterring your username.

## Additional context or screenshots (if appropriate)
No repro on Android.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Windows UWP --> Xbox One

Used versions:
- Kodi version: most recent
- Retrospect version: most recent

**Comment by basrieter** [comment] 2019-11-25 15:35
Please do this:

- enable debug logging in Retrospect
- try setting the password again
- upload the log via the built-in Retrospect functionality
- post the link to the log (please verify it works) here

**Comment by basrieter** [comment] 2019-12-08 19:42
Any update on this?

**Comment by eettiennee** [comment] 2019-12-09 12:27
I'm sure for the delay. The problem is that also the debug logging is crashing so I'm not able to provide you with logs.
I've switched to another device than my Xbox to bypass the problem. You can close this bug if you want because I can't be more helpfull in case you are not able to repro.

**Comment by basrieter** [comment] 2019-12-09 22:40
Duplicate of #1225 I assume.

**Closed by basrieter** 2019-12-09 22:40 UTC
Labels: bug, duplicate
